### ISSUE TITLE
odd number of players

### ISSUE THREAD

**Issue by KrysKatrod** [wsfrance/PairingSofware#25]
error when you do a tournament with an odd number of players.

log :

Cleaning up console
Cleaning up variables
MATLAB has experienced a low-level graphics error, and may not have drawn correctly.
Read about what you can do to prevent this issue by running this command: opengl problems,
then restart MATLAB.
To share details of this issue with MathWorks technical support, please
include this file with your service request: C:\Users\BOBARC~1\AppData\Local\Temp\jogl.ex.3720
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Bushiroad Pairing Software
Author: malganis35
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Opening of the software
- Change automatically the directory
- Add paths : subfunctions, externalLibs, etc.
- Quit the Application
- Quit Excel
-- Fail
- Quit Acrobat
Erreur : le processus "Acrobat.exe" est introuvable. 
-- Success
- Visibility off for tournament elements of GUI
- Generate Tables from local DB: tablePlayers_fromDB and tablePlayers_forTournament / Refresh Local DB
-- Refreshing the local Databases
-- 1 file(s) were found locally: 
    'fileforsw.csv'

-- Importing each database
--- Importing: ../data/playerDB/fileforsw.csv
--- Delete false characters (like ", etc.)
--- Set Capital Letters to selected columns : name, familyName, pseudo
-- Create the variable TABLE.tablePlayers_forTournament
No caseInsensitiveOption. Putting by default to true
This is SORT BY
- Initialize functions (@cellSelect) to Tables
- Display Logo on the Software
- Delete all files in /export
No caseInsensitiveOption. Putting by default to true
No caseInsensitiveOption. Putting by default to true
No caseInsensitiveOption. Putting by default to true
This is SORT BY
This is SORT BY
This is SORT BY
This is SORT BY
This is SORT BY
This is SORT BY
This is SORT BY
This is SORT BY
This is SORT BY
This is SORT BY
This is SORT BY
This is SORT BY
This is SORT BY
This is SORT BY
This is SORT BY
This is SORT BY
This is SORT BY
Yes coming right up. Shuffling player seed
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Tournament Run
Author: malganis35
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
--------------------------------------------------------------------
Start the Tournament Core
- Set the title of the window
- Look if we start from a save file or a new tournament
-- This is a new tournament. Set boolean to 1 and typeRound = Round
-- Update the list of Players in the handles.LIST_listPlayer
-- Initialize the subTables and a Matrice to store already done match (such that a match cannot be re-done)
-- Initialize the table tablePlayers_forTournament
-- Set the option of columns to display
-- Initialize the table pairingTable and its allocation
-- Initialize the table HistoryTable to store the standing at each round
-- Set the callbacks of the tables
--------------------------------------------------------------------
Start the function to pair players
- Incremente number of rounds
Save the actual Table of tournament for replay
- Create Pairing for Round no.1
-- Creating pairing for 1st round
Warning: Integer operands are required for colon operator when used as index
> In swissRound>firstRoundPairing (line 73)
  In swissRound (line 25)
  In beginTournament>BUT_pair_Callback (line 281)
  In gui_mainfcn (line 95)
  In beginTournament (line 42)
  In matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)beginTournament('BUT_pair_Callback',hObject,eventdata,guidata(hObject))
Warning: Integer operands are required for colon operator when used as index
> In swissRound>firstRoundPairing (line 74)
  In swissRound (line 25)
  In beginTournament>BUT_pair_Callback (line 281)
  In gui_mainfcn (line 95)
  In beginTournament (line 42)
  In matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)beginTournament('BUT_pair_Callback',hObject,eventdata,guidata(hObject))
Index exceeds matrix dimensions.

Error in swissRound>firstRoundPairing (line 74)

Error in swissRound (line 25)

Error in beginTournament>BUT_pair_Callback (line 281)

Error in gui_mainfcn (line 95)

Error in beginTournament (line 42)

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)beginTournament('BUT_pair_Callback',hObject,eventdata,guidata(hObject))

Error while evaluating UIControl Callback

**Comment by wsfrance** [comment]
has to be resolved by using a ghost player

**Comment by malganis35** [comment]
correct : add a BYE player when it is odd

continue ..
